### ISSUE TITLE
RuntimeError: Please use nest_asyncio.apply() to allow nested event loops

### ISSUE THREAD

**Issue by vdesaintpern** [awslabs/graphrag-toolkit#3]
I'm trying to evaluate graphrag-toolkit.

Just created the AWS resources and testing with provided source code in fresh new conda env with pip install found in doc.

Please note I checked apply() was present and it is. No change in provided code.

```
2024-11-29 15:36:59:INFO:g.i.e.extraction_pipeline:Running extraction pipeline [batch_size: 4, num_workers: 2]
2024-11-29 15:37:08:INFO:g.i.e.extraction_pipeline:Running extraction pipeline [batch_size: 4, num_workers: 2]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/ingestion/pipeline.py", line 734, in arun
    loop.run_in_executor(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/base_events.py", line 863, in run_in_executor
    executor.submit(func, *args), loop=self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/concurrent/futures/process.py", line 830, in submit
    self._adjust_process_count()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/concurrent/futures/process.py", line 789, in _adjust_process_count
    self._spawn_process()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/concurrent/futures/process.py", line 807, in _spawn_process
    p.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 38, in asyncio_run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/vivieper/code/technical-notes/GenAI/Playground/graphrag-toolkit/test.py", line 35, in <module>
    graph_index.extract_and_build(docs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/lexical_graph_index.py", line 251, in extract_and_build
    nodes | extraction_pipeline | build_pipeline | sink_fn
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/pipe.py", line 42, in __ror__
    return self.function(other)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/pipe.py", line 36, in <lambda>
    self.function = lambda iterable, *args2, **kwargs2: function(
                                                        ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/utils/pipeline_utils.py", line 8, in _sink_from
    for item in generator:
                ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/build/build_pipeline.py", line 98, in build
    for chunks in iter_batch(nodes, (self.num_workers * self.batch_size)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/utils.py", line 254, in iter_batch
    b = list(islice(source_iter, size))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/extract/extraction_pipeline.py", line 111, in extract
    async_results = asyncio_run(self.ingestion_pipeline.arun(nodes=docs, num_workers=self.num_workers, show_progress=self.show_progress))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 40, in asyncio_run
    raise RuntimeError(
RuntimeError: Detected nested async. Please use nest_asyncio.apply() to allow nested event loops.Or, use async entry methods like `aquery()`, `aretriever`, `achat`, etc.
2024-11-29 15:37:09:INFO:g.i.e.extraction_pipeline:Running extraction pipeline [batch_size: 4, num_workers: 2]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/ingestion/pipeline.py", line 734, in arun
    loop.run_in_executor(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/base_events.py", line 863, in run_in_executor
    executor.submit(func, *args), loop=self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/concurrent/futures/process.py", line 830, in submit
    self._adjust_process_count()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/concurrent/futures/process.py", line 789, in _adjust_process_count
    self._spawn_process()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/concurrent/futures/process.py", line 807, in _spawn_process
    p.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 38, in asyncio_run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/vivieper/code/technical-notes/GenAI/Playground/graphrag-toolkit/test.py", line 35, in <module>
    graph_index.extract_and_build(docs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/lexical_graph_index.py", line 251, in extract_and_build
    nodes | extraction_pipeline | build_pipeline | sink_fn
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/pipe.py", line 42, in __ror__
    return self.function(other)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/pipe.py", line 36, in <lambda>
    self.function = lambda iterable, *args2, **kwargs2: function(
                                                        ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/utils/pipeline_utils.py", line 8, in _sink_from
    for item in generator:
                ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/build/build_pipeline.py", line 98, in build
    for chunks in iter_batch(nodes, (self.num_workers * self.batch_size)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/utils.py", line 254, in iter_batch
    b = list(islice(source_iter, size))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/extract/extraction_pipeline.py", line 111, in extract
    async_results = asyncio_run(self.ingestion_pipeline.arun(nodes=docs, num_workers=self.num_workers, show_progress=self.show_progress))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 40, in asyncio_run
    raise RuntimeError(
RuntimeError: Detected nested async. Please use nest_asyncio.apply() to allow nested event loops.Or, use async entry methods like `aquery()`, `aretriever`, `achat`, etc.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 316, in __step_run_and_handle_result
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/ingestion/pipeline.py", line 747, in arun
    result: List[List[BaseNode]] = await asyncio.gather(*tasks)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
    future.result()
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 38, in asyncio_run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
RuntimeError: cannot reuse already awaited coroutine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vivieper/code/technical-notes/GenAI/Playground/graphrag-toolkit/test.py", line 35, in <module>
    graph_index.extract_and_build(docs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/lexical_graph_index.py", line 251, in extract_and_build
    nodes | extraction_pipeline | build_pipeline | sink_fn
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/pipe.py", line 42, in __ror__
    return self.function(other)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/pipe.py", line 36, in <lambda>
    self.function = lambda iterable, *args2, **kwargs2: function(
                                                        ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/utils/pipeline_utils.py", line 8, in _sink_from
    for item in generator:
                ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/build/build_pipeline.py", line 98, in build
    for chunks in iter_batch(nodes, (self.num_workers * self.batch_size)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/utils.py", line 254, in iter_batch
    b = list(islice(source_iter, size))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/graphrag_toolkit/indexing/extract/extraction_pipeline.py", line 111, in extract
    async_results = asyncio_run(self.ingestion_pipeline.arun(nodes=docs, num_workers=self.num_workers, show_progress=self.show_progress))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/graphrag-toolkit-2/lib/python3.12/site-packages/llama_index/core/async_utils.py", line 40, in asyncio_run
    raise RuntimeError(
RuntimeError: Detected nested async. Please use nest_asyncio.apply() to allow nested event loops.Or, use async entry methods like `aquery()`, `aretriever`, `achat`, etc.
```

**Comment by vdesaintpern** [comment]
Please note that adding it to a "if __name__ == '__main__':" section solves the issue. Suggesting to update readme to avoid confusion.

**Comment by zhaoyuhong5** [comment]
Here is a brief explanation of using `nest_asyncio.apply()` to allow nested event loops in Python:

### Introduction

In Python, by default, running an event loop inside another existing event loop is not allowed and will raise errors. However, the `nest_asyncio` library provides a way to overcome this limitation. The `nest_asyncio.apply()` function is used to enable nested event loops, which can be useful in various scenarios like when working with multiple asynchronous frameworks or when you want to run asynchronous code within an already running event loop context.

### Code Example and Explanation

1. **Installation**:
First, you need to install the `nest_asyncio` library if it's not already installed. You can do this using `pip install nest_asyncio`.

2. **Basic Usage**:
Here is a simple code snippet to demonstrate how `nest_asyncio.apply()` works:
```python
import asyncio
import nest_asyncio

# Apply the function to allow nested event loops
nest_asyncio.apply()

async def inner_async_function():
    print("Inside inner async function")
    await asyncio.sleep(1)

async def outer_async_function():
    print("Starting outer async function")
    await inner_async_function()
    print("Finished outer async function")

# Run the outer async function
asyncio.run(outer_async_function())
```
In this example:
- First, we import the necessary libraries `asyncio` and `nest_asyncio`.
- Then we call `nest_asyncio.apply()` to modify the default behavior and allow nested event loops.
- We define two asynchronous functions: `inner_async_function` which simply prints a message and sleeps for 1 second, and `outer_async_function` which calls the inner function.
- Finally, we use `asyncio.run()` to execute the `outer_async_function`. Thanks to `nest_asyncio.apply()`, the inner async function can be executed within the context of the outer one without issues related to nested event loops.

### Use Cases

This can be particularly handy in situations where you might be integrating different asynchronous libraries or when you have code that needs to run asynchronously within an environment that already has an ongoing event loop, such as in some Jupyter Notebook scenarios or when combining multiple async frameworks like `aiohttp` with other async code.

Overall, `nest_asyncio.apply()` provides a convenient solution to enable nested event loops and make it easier to handle complex asynchronous programming situations in Python.

**Comment by vdesaintpern** [comment]
Thanks for the explanations. Still, provided code fails and I believe this would be beneficial for most to have an accurate way to test the toolkit.

**Comment by iansrobinson** [comment]
Hi @vdesaintpern 

Thanks for your message. The examples in the readme, documentation and sample notebooks all use `nest_asyncio.apply()`. Is there something else that is missing?

Thanks

ian

**Comment by vdesaintpern** [comment]
> Hi @vdesaintpern
> 
> Thanks for your message. The examples in the readme, documentation and sample notebooks all use `nest_asyncio.apply()`. Is there something else that is missing?
> 
> Thanks
> 
> ian

Thanks for you answer Ian.

Bottom line is if you run the provided code, containing the apply(), it fails. I think it would be great to fix this so that new users can test without wondering why they get this error. I've been able to fix it myself adding the code to a  "if name == 'main':" section. This could be useful for others.

**Comment by iansrobinson** [comment]
Please would you provide more details of your setup environment so that I can try and reproduce this.  `nest_asyncio.apply()` has worked in the environments where we've tested the install previously, including the SageMaker Jupyter notebooks created through the CloudFormation template in the examples.

Thanks

**Comment by vdesaintpern** [comment]
I created the AWS resources needs (Neptune, opensearch serverless and systems manager tunnel to get to Neptune through a jumpbox), created a new conda env, activated it, pip installed graph-toolkit, create a new .py file, copy pasted the indexing code provided then ran it.

**Comment by vdesaintpern** [comment]
Then I changed the provide code to this and it worked:

```
from graphrag_toolkit import LexicalGraphIndex
from graphrag_toolkit.storage import GraphStoreFactory
from graphrag_toolkit.storage import VectorStoreFactory

from llama_index.readers.web import SimpleWebPageReader

import nest_asyncio
nest_asyncio.apply()

doc_urls = [
    'https://docs.aws.amazon.com/neptune/latest/userguide/intro.html',
    'https://docs.aws.amazon.com/neptune-analytics/latest/userguide/what-is-neptune-analytics.html',
    'https://docs.aws.amazon.com/neptune-analytics/latest/userguide/neptune-analytics-features.html',
    'https://docs.aws.amazon.com/neptune-analytics/latest/userguide/neptune-analytics-vs-neptune-database.html'
]

if __name__ == '__main__':
    docs = SimpleWebPageReader(
        html_to_text=True,
        metadata_fn=lambda url:{'url': url}
    ).load_data(doc_urls)

    graph_store = GraphStoreFactory.for_graph_store(
        'neptune-db://db-graphrag-test.cluster-c3qxek8vng6o.us-west-2.neptune.amazonaws.com:9192'
    )

    vector_store = VectorStoreFactory.for_vector_store(
        'aoss://https://0tj278kbgm6pidvai5v2.us-west-2.aoss.amazonaws.com'
    )

    graph_index = LexicalGraphIndex(
        graph_store, 
        vector_store
    )

    graph_index.extract_and_build(docs)
```

**Comment by iansrobinson** [comment]
Thank you. I'll try and reproduce (probably beginning of next week now), and work out why `if __name__ == '__main__':` makes a difference for this kind of setup.

**Comment by iansrobinson** [comment]
Hi @vdesaintpern Just following up on our offline conversation from last week.

This behaviour is as expected when running an application (versus running examples in a Jupyter notebook), though it's not always reproducible across environments: I've not witnessed it using conda and Python 3.12 on an EC2 instance, but it is evident when running application code on a Mac.

The fix, as you've indicated, is to put your application logic inside a method, and add an `if name == 'main' block`.

I've updated the examples on the landing page, added an [FAQ item](https://github.com/awslabs/graphrag-toolkit/blob/main/docs/faq.md#runtimeerror-please-use-nest_asyncioapply-to-allow-nested-event-loops), and included instructions at the head of any example-heavy documentation pages.

Thanks for raising this

ian
